### ISSUE TITLE
Produce Update 28 Release

### ISSUE THREAD

**Issue by gtav-ent** [gtav-ent/GTAV-EnhancedNativeTrainer#125]
This needs:
- [x] prop spawner issue #115
- [x] prop spawner issue #116
- [x] prop spawner issue #117
- [x] prop spawner miscellany: teleport to (near) prop option
- [x] prop spawner miscellany: enforce and provide help on apparent 250 object limit
- [x] prop spawner miscellany: possibly import and export to XML?
- [x] prop spawner miscellany: more & more appropriate movement speeds

and
- [x] find out why something in this version (prop movement?) has been intermittently crashing the game
- [x] refactor the bodyguard stuff so it continues to reuse code but appears separately in the menu system
- [x] detect whether nkjellman's mod is present and if so, make the carrier teleport locations etc available
- [x] possibly add ped scenarios, issue #82
- [x] improve skin-reset-on-death behaviour, which crashes again in the latest game versions
- [x] sanitise menu headings to remove characters that can't be shown with chosen font
- [x] fix bodyguard behaviour using old commits as pointed out by RK
- [x] custom skin option
- [x] custom object option?
- [x] review and testing of changes
- [x] write the release notes
